version: '3'
services:
  db:
    image: mysql:8.0
    # container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: express_sample_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    # volumes:
    #   - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - 8080:3000
    tty: true
    command: npm run dev
    volumes:
      - ./app:/app
    working_dir: /app
    links:
      - db
      - db:database
    depends_on:
      - db